# Generated by Django 3.2.24 on 2024-03-05 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Smart_EV_App', '0002_station'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=30, null=True)),
                ('model_no', models.CharField(max_length=30, null=True)),
                ('registration_no', models.CharField(max_length=30, null=True)),
                ('chassi_no', models.CharField(max_length=30, null=True)),
                ('engine_no', models.CharField(max_length=30, null=True)),
                ('battery_capacity', models.CharField(max_length=30, null=True)),
                ('is_enabled', models.IntegerField(default=1)),
                ('created_date', models.DateTimeField(null=True)),
                ('updated_date', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Smart_EV_App.user')),
            ],
            options={
                'db_table': 'vehicles',
            },
        ),
    ]
