# Generated by Django 3.2.24 on 2024-04-16 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Smart_EV_App', '0004_battery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='battery',
            old_name='charge',
            new_name='status',
        ),
    ]
